project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - examples/basic.qmd
    - examples/revealjs.qmd

website:
  title: "quarto-shapes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Examples
        menu:
          - href: examples/basic.qmd
            text: Basic Usage
          - href: examples/revealjs.qmd
            text: RevealJS Slides

format:
  html:
    theme: cosmo
    toc: true

filters:
  - shapes
